// Generated by CoffeeScript 1.12.7
(function() {
  var filter;

  filter = require("../../core/methods/filter.js");

  module.exports = {
    accepted: [false, Array, Function, Number, String],
    value: false
  };

}).call(this);
