// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    accepted: [Boolean],
    flipped: {
      accepted: [Boolean],
      value: false
    },
    value: false
  };

}).call(this);
