// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    accepted: [false, Function, String],
    sort: {
      accepted: ["asc", "desc"],
      value: "asc"
    },
    value: false
  };

}).call(this);
